import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

abstract class GenerateAppVersionTask : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val manifestFile: RegularFileProperty

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val manifest = manifestFile.get().asFile
        if (!manifest.exists()) {
            throw GradleException("Missing update/manifest.json")
        }
        val manifestText = manifest.readText(Charsets.UTF_8)
        val channel = extractString(manifestText, "channel")
            ?: throw GradleException("update/manifest.json channel is required.")
        val versionName = extractString(manifestText, "versionName")
            ?: throw GradleException("update/manifest.json versionName is required.")
        val versionCode = extractLong(manifestText, "versionCode")
            ?: throw GradleException("update/manifest.json versionCode must be a number.")

        val generated = buildString {
            appendLine("package me.thenano.yamibo.yamibo_app")
            appendLine()
            appendLine("// Generated by :composeApp:generateAppVersion from update/manifest.json. Do not edit manually.")
            appendLine("object AppVersion {")
            appendLine("    const val Channel: String = \"${channel.escapeKotlin()}\"")
            appendLine("    const val VersionName: String = \"${versionName.escapeKotlin()}\"")
            appendLine("    const val VersionCode: Long = $versionCode")
            appendLine()
            appendLine("    const val displayName: String = \"\$Channel-v\$VersionName\"")
            appendLine("}")
        }

        val destination = outputFile.get().asFile
        destination.parentFile.mkdirs()
        destination.writeText(generated, Charsets.UTF_8)
    }

    private fun extractLong(json: String, field: String): Long? =
        Regex(""""${Regex.escape(field)}"\s*:\s*(\d+)""")
            .find(json)
            ?.groupValues
            ?.get(1)
            ?.toLongOrNull()

    private fun extractString(json: String, field: String): String? =
        Regex(""""${Regex.escape(field)}"\s*:\s*"([^"]*)"""")
            .find(json)
            ?.groupValues
            ?.get(1)

    private fun String.escapeKotlin(): String =
        buildString {
            this@escapeKotlin.forEach { char ->
                when (char) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(char)
                }
            }
        }
}
