import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

abstract class GenerateRestorableScreenRegistryTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val sourceDir: DirectoryProperty

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val annotationPattern = Regex(
            """@RestorableScreenEntry(?:\([^)]*\))?\s+(?:data\s+)?(?:class|object)\s+([A-Za-z_][A-Za-z0-9_]*)""",
        )
        val packagePattern = Regex("""(?m)^\uFEFF?package\s+([A-Za-z_][A-Za-z0-9_\.]*)""")
        val sourceRoot = sourceDir.get().asFile
        val entries = sourceRoot
            .walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .flatMap { file ->
                val text = file.readText(Charsets.UTF_8)
                val matches = annotationPattern.findAll(text).toList()
                if (matches.isEmpty()) {
                    return@flatMap emptyList<String>()
                }
                val packageName = packagePattern.find(text)?.groupValues?.get(1)
                    ?: error("Missing package declaration in ${file.relativeTo(sourceRoot)}")
                matches.map { match ->
                    "$packageName.${match.groupValues[1]}.Decoder"
                }
            }
            .distinct()
            .sortedWith(String.CASE_INSENSITIVE_ORDER)
            .toList()

        check(entries.isNotEmpty()) {
            "No @RestorableScreenEntry classes found under $sourceRoot"
        }

        val generated = buildString {
            appendLine("package me.thenano.yamibo.yamibo_app.navigation")
            appendLine()
            appendLine("// Generated by :composeApp:generateRestorableScreenRegistry. Do not edit manually.")
            appendLine("internal val generatedRestorableScreenDecoders: List<RestorableNavigatableDecoder> = listOf(")
            entries.forEach { entry ->
                appendLine("    $entry,")
            }
            appendLine(")")
        }

        val destination = outputFile.get().asFile
        destination.parentFile.mkdirs()
        destination.writeText(generated, Charsets.UTF_8)
    }
}
