import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

abstract class ValidateUpdateManifestTask : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val manifestFile: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val stableFile: RegularFileProperty

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val changelogsDir: DirectoryProperty

    @get:Input
    abstract val appVersionCode: Property<Long>

    @get:Input
    abstract val appVersionName: Property<String>

    @TaskAction
    fun validate() {
        val manifest = manifestFile.get().asFile
        val stable = stableFile.get().asFile
        if (!manifest.exists()) {
            throw GradleException("Missing update/manifest.json")
        }
        if (!stable.exists()) {
            throw GradleException("Missing update/stable.json. Run ./gradlew syncStableManifest first.")
        }

        val manifestText = manifest.readText(Charsets.UTF_8)
        val stableText = stable.readText(Charsets.UTF_8)
        if (manifestText.trim() != stableText.trim()) {
            throw GradleException("update/stable.json is out of sync with update/manifest.json. Run ./gradlew syncStableManifest.")
        }

        val manifestVersionCode = extractLong(manifestText, "versionCode")
            ?: throw GradleException("update/manifest.json versionCode must be a number.")
        val manifestVersionName = extractString(manifestText, "versionName")
            ?: throw GradleException("update/manifest.json versionName is required.")
        val manifestIsReady = extractBoolean(manifestText, "isReady")
            ?: throw GradleException("update/manifest.json isReady must be a boolean and must be false in source manifests.")

        val expectedVersionCode = appVersionCode.get()
        val expectedVersionName = appVersionName.get()
        if (manifestVersionCode != expectedVersionCode) {
            throw GradleException("versionCode mismatch: composeApp=$expectedVersionCode, update/manifest.json=$manifestVersionCode")
        }
        if (manifestVersionName != expectedVersionName) {
            throw GradleException("versionName mismatch: composeApp=$expectedVersionName, update/manifest.json=$manifestVersionName")
        }
        if (manifestIsReady) {
            throw GradleException("Source update manifests must keep isReady=false. Published ready manifests are generated by the release workflow only.")
        }
        if (hasField(manifestText, "releaseUrl")) {
            throw GradleException("Source update manifests must not contain releaseUrl while isReady=false.")
        }
        if (!isEmptyArray(manifestText, "assets")) {
            throw GradleException("Source update manifests must keep assets=[] while isReady=false.")
        }

        val changelog = changelogsDir.file("$manifestVersionCode.changelog").get().asFile
        if (!changelog.exists() || changelog.readText(Charsets.UTF_8).isBlank()) {
            throw GradleException("Missing or empty update/changelogs/$manifestVersionCode.changelog")
        }
    }

    private fun extractLong(json: String, field: String): Long? =
        Regex(""""${Regex.escape(field)}"\s*:\s*(\d+)""")
            .find(json)
            ?.groupValues
            ?.get(1)
            ?.toLongOrNull()

    private fun extractString(json: String, field: String): String? =
        Regex(""""${Regex.escape(field)}"\s*:\s*"([^"]*)"""")
            .find(json)
            ?.groupValues
            ?.get(1)

    private fun extractBoolean(json: String, field: String): Boolean? =
        Regex(""""${Regex.escape(field)}"\s*:\s*(true|false)""")
            .find(json)
            ?.groupValues
            ?.get(1)
            ?.toBooleanStrictOrNull()

    private fun hasField(json: String, field: String): Boolean =
        Regex(""""${Regex.escape(field)}"\s*:""").containsMatchIn(json)

    private fun isEmptyArray(json: String, field: String): Boolean =
        Regex(""""${Regex.escape(field)}"\s*:\s*\[\s*]""", RegexOption.DOT_MATCHES_ALL).containsMatchIn(json)
}
